


apiVersion: v1
kind: Namespace
metadata:
  name:   config-service


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  config-deployment
  namespace: config-service
  labels:
    app:  config-deployment
spec:
  selector:
    matchLabels:
      app: config-deployment
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  config-deployment
    spec:
      containers:
      - name:  config-deployment
        image: philipasd/config_service
        imagePullPolicy: Always
        ports:
        - containerPort:  8088
          protocol: TCP
          name:  config-deployment

---

apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: config-service
spec:
  selector:
    app: config-service
  type: ClusterIP
  ports:
  - name: config-service
    protocol: TCP
    port: 80
    targetPort: 8088