

apiVersion: v1
kind: Namespace
metadata:
  name:  mongo-service

---

apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mongo-service
spec:
  ports:
  - port: 27017
    name: peer
  clusterIP: None
  selector:
    app: mongo