
apiVersion: v1
kind: Namespace
metadata:
  name:  friend-service



---
apiVersion: v1
kind: ConfigMap
metadata:
  name: friend-configmap
  namespace: friend-service

data:
  server.port: "7001"
  SPRING_PROFILES_ACTIVE: docker
