apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx
  namespace: default
  labels:
    app:  nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app:  nginx
    spec:
      containers:
      - name:  nginx
        image:  philipasd/app:v1.0.0
        ports:
        - containerPort:  80
          name:  nginx
---


        
---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: default
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - name: api-gateway-service
    protocol: TCP
    port: 80 