---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx
  namespace: prod
  labels:
    app:  nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app:  nginx
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  nginx
        image:  philipasd/app:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort:  80
   