




---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: friend-deployment
  namespace: friend-service
spec:
  selector:
    matchLabels:
      app: friend-deployment
  template:
    metadata:
      labels:
        app: friend-deployment
    spec:
      containers:
      - name: friend-deployment
        image: philipasd/friend_service
        imagePullPolicy: Always
        
        ports:
        - containerPort: 7001

        env:
        - name:  SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name:  friend-configmap
              key:  SPRING_PROFILES_ACTIVE

---

apiVersion: v1
kind: Service
metadata:
  name: friend-service
  namespace: friend-service

spec:
  type: ClusterIP
  selector:
    app: friend-deployment
  ports:
  - name: http
    port: 80
    targetPort: 7001
