apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discovery-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: discovery-deployment # has to match .spec.template.metadata.labels
  serviceName: "discovery-deployment"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: discovery-deployment # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: discovery-deployment
        image: philipasd/discovery_service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8761

---

apiVersion: v1
kind: Service
metadata:
  name: discovery-deployment
  namespace: default
spec:
  selector:
    app: discovery-deployment
  ports:
  - name: discovery-deployment
    protocol: TCP
    port: 8761

---

# load balancer service
apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
spec:
  type: NodePort
  selector:
    app: discovery-deployment
  ports:
    - port: 80
      targetPort: 8761