apiVersion: apps/v1
kind: Deployment
metadata:
  name:  redis-deployment
  namespace: default
  labels:
    app:  redis-deployment
spec:
  selector:
    matchLabels:
      app: redis-deployment
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  redis-deployment
    spec:
      containers:
      - name:  redis-deployment
        image: bitnami/redis:latest
        imagePullPolicy: Always
        ports:
        - containerPort:  6379
          name:  redis-deployment
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis-deployment
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379